name: forestcatering-premium
display_name: ForestCatering Premium
version: 1.0.1
author:
  name: ForestCatering
  email: kontakt@forestcatering.pl

meta:
  compatibility:
    from: 9.0.0
    to: 9.99.99
  available_layouts:
    layout-full-width:
      name: Full width
      description: Page without side columns
    layout-both-columns:
      name: Both columns
      description: Page with left and right side columns
    layout-left-column:
      name: Left column
      description: Page with only the left side column
    layout-right-column:
      name: Right column
      description: Page with only the right side column
  default_layout: layout-full-width

parent: classic

assets:
  use_parent_assets: true
  css:
    all:
      - id: fc-theme
        path: assets/css/theme.css
        priority: 200
