name: forestcatering-premium
display_name: ForestCatering Premium
version: 1.0.0
author:
  name: ForestCatering
  email: kontakt@forestcatering.pl
  url: https://forestcatering.pl
meta:
  compatibility:
    from: 9.0.0
    to: ~
  available_layouts:
    layout-full-width:
      name: Full Width
      description: No side columns, ideal for distraction-free pages such as product pages.
    layout-both-columns:
      name: Three Columns
      description: One large central column and 2 side columns.
    layout-left-column:
      name: Two Columns, small left column
      description: Two columns with a small left column
    layout-right-column:
      name: Two Columns, small right column
      description: Two columns with a small right column
parent: classic
assets:
  use_parent_assets: true
  css:
    all:
      - id: forestcatering-theme
        path: assets/css/theme.css
        priority: 250
  js:
    all:
      - id: forestcatering-theme
        path: assets/js/theme.js
        priority: 250
global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
theme_settings:
  default_layout: layout-full-width
